name: Feature request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing ideas to improve this project!

  - type: input
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
      placeholder: "e.g., Easier CSV export"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Feature Description
      description: Describe the functionality you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other ways to solve the problem?